"use client";

import { View, Text } from "@react-pdf/renderer";
import { styles } from "../styles";
import BookPageLayout from "../components/BookPageLayout";
import DeploymentArchitecture from "../diagrams/DeploymentDiagram";

export default function Implementation() {
  return (
    <BookPageLayout chapterTitle="Implementation" chapterNum="08">
      <View style={{ marginBottom: 28, alignItems: "center", marginTop: 20 }}>
        <Text
          style={{
            fontSize: 11,
            fontFamily: "Times-Roman",
            color: "#666666",
            letterSpacing: 4,
            textTransform: "uppercase",
            marginBottom: 8,
          }}
        >
          Chapter 08
        </Text>
        <Text
          style={{
            fontSize: 26,
            fontFamily: "Times-Bold",
            textAlign: "center",
            letterSpacing: 1.5,
            textTransform: "uppercase",
            color: "#000000",
          }}
        >
          Implementation
        </Text>
        <View
          style={{
            width: 60,
            height: 2,
            backgroundColor: "#000000",
            marginTop: 12,
          }}
        />
      </View>

      <Text style={styles.h2}>8.1 Introduction</Text>
      <Text style={styles.paragraphIndent}>
        The implementation phase translates the system design blueprints into executable code. For Dino-Ecommerce, this involved leveraging the Django framework to build out the database models, implement the business logic inside views, and construct the user interface using HTML templates and Bootstrap. This chapter highlights critical code sections that demonstrate the platform's core functionalities.
      </Text>

      <Text style={styles.h2}>8.2 Core Django Models</Text>
      <Text style={styles.paragraphIndent}>
        The foundation of the application resides in `core/models.py`. The Django ORM translates these Python classes into database tables. The most critical model is the `Order`, which links users, their selected items, and billing information.
      </Text>

      {/* Code Snippet: Models */}
      <View style={{ backgroundColor: "#f4f4f4", padding: 12, borderRadius: 4, marginBottom: 16 }}>
        <Text style={{ fontFamily: "Courier", fontSize: 9, lineHeight: 1.4 }}>
          {`class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)`}
        </Text>
      </View>
      <Text style={styles.paragraph}>
        This snippet demonstrates relational database mapping using `ForeignKey` and `ManyToManyField`, crucial for linking a user's session to their persistent cart and eventual payment history.
      </Text>

      <Text style={styles.h2}>8.3 Stripe Payment Integration (Views)</Text>
      <Text style={styles.paragraphIndent}>
        The checkout process requires secure communication with the Stripe API. Inside `core/views.py`, the `PaymentView` handles the post-request containing the Stripe token generated by the frontend.
      </Text>

      {/* Code Snippet: Views */}
      <View style={{ backgroundColor: "#f4f4f4", padding: 12, borderRadius: 4, marginBottom: 16 }}>
        <Text style={{ fontFamily: "Courier", fontSize: 9, lineHeight: 1.4 }}>
          {`class PaymentView(View):
    def post(self, request, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = request.POST.get('stripeToken')
        amount = int(order.get_total() * 100) # Stripe uses cents

        try:
            charge = stripe.Charge.create(
                amount=amount,
                currency="usd",
                source=token,
                description=f"Charge for {request.user.username}"
            )
            # Create payment record
            payment = Payment(
                stripe_charge_id=charge['id'],
                user=self.request.user,
                amount=order.get_total()
            )
            payment.save()
            order.ordered = True
            order.payment = payment
            order.save()
            
            messages.success(self.request, "Order was successful!")
            return redirect("/")
            
        except stripe.error.CardError as e:
            messages.warning(self.request, f"Card Error: {e}")
            return redirect("/payment/stripe/")`}
        </Text>
      </View>
      <Text style={styles.paragraph}>
        This view utilizes robust error handling (`try/except`) to manage Stripe-specific exceptions, ensuring that if a card declines, the application fails gracefully, alerts the user via Django's messaging framework, and redirects them to try again.
      </Text>

      <Text style={styles.h2}>8.4 Frontend Templating</Text>
      <Text style={styles.paragraphIndent}>
        Django uses a powerful templating engine that allows Python code to be embedded within HTML. The cart view (`order_snippet.html`) dynamically calculates and displays order totals.
      </Text>

      {/* Code Snippet: Templates */}
      <View style={{ backgroundColor: "#f4f4f4", padding: 12, borderRadius: 4, marginBottom: 16 }}>
        <Text style={{ fontFamily: "Courier", fontSize: 9, lineHeight: 1.4 }}>
          {`<!-- order_snippet.html -->
<table class="table">
  <tbody>
    {% for order_item in object.items.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ order_item.item.title }}</td>
      <td>
        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
          <i class="fas fa-minus mr-2"></i>
        </a>
        {{ order_item.quantity }}
        <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
          <i class="fas fa-plus ml-2"></i>
        </a>
      </td>
      <td>
        {% if order_item.item.discount_price %}
            $\{{ order_item.get_total_discount_item_price }}
            <span class="badge badge-primary">Saving $\{{ order_item.get_amount_saved }}</span>
        {% else %}
            $\{{ order_item.get_total_item_price }}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>`}
        </Text>
      </View>

      <Text style={styles.h2}>8.5 Application Deployment</Text>
      <Text style={styles.paragraphIndent}>
        Local development utilized `python manage.py runserver` with SQLite. For production deployment, the application architecture was designed to be cloud-agnostic, supporting standard WSGI servers. A typical deployment utilizes Gunicorn to serve the Django application, with static assets (CSS/JS) managed by WhiteNoise or an external CDN. 
      </Text>
      <Text style={styles.paragraph}>
        Environment variables (`SECRET_KEY`, `STRIPE_SECRET_KEY`) are utilized extensively to ensure secure deployment practices across environments.
      </Text>

      {/* Deployment Diagram */}
      <View style={{ marginTop: 24, marginBottom: 24 }}>
        <DeploymentArchitecture />
        <Text style={{ textAlign: "center", fontSize: 10, fontFamily: "Times-Italic", marginTop: 8, color: "#666666" }}>
          Figure 8.1: Typical Production Deployment Architecture
        </Text>
      </View>

    </BookPageLayout>
  );
}
